name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Stating Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
        if: always()
      - name: build production project
        run: yarn build:prod
        if: always()
      - name: linting typescript
        run: yarn lint:ts
        if: always()
      - name: linting scss
        run: yarn lint:scss
        if: always()
      - name: unit testing
        run: yarn test:unit
        if: always()
      - name: build storybook
        run: yarn sb:build
        if: always()
      - name: screenshot testing
        run: yarn test:ui:ci
        if: always()
